name: anki_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  gap: ^3.0.1
  go_router: ^16.2.1
  go_router_builder: ^2.7.1
  hooks_riverpod: ^2.6.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.4.13
  riverpod_generator: ^2.3.10
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
